### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by Jawadllo** [monniert/unicorn#3]
hi , I'm new in AI
I'm  training the model from scratch i download the dataset and the package   

I run in google colab:
!cuda=GPU-f491dbb6-2dc7-a094-5417-a57de28df194  config=p3d_car.yml tag=run_tag  /content/unicorn-main\scripts\pipeline.sh

this appears to me:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/scipy/io/matlab/mio.py", line 39, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: '/content/unicorn-main/datasets/pascal_3d/ucmr_anno/data/car_train.mat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/unicorn-main/src/trainer.py", line 292, in <module>
    trainer = Trainer(cfg, run_dir, seed=seed)
  File "/content/unicorn-main/src/utils/__init__.py", line 104, in wrapper
    return f(*args, **kw)
  File "/content/unicorn-main/src/trainer.py", line 41, in __init__
    self.train_loader, self.val_loader, self.test_loader = create_train_val_test_loader(cfg, rank, world_size)
  File "/content/unicorn-main/src/dataset/__init__.py", line 16, in create_train_val_test_loader
    train = get_dataset(name)(split="train", **kwargs)
  File "/content/unicorn-main/src/dataset/p3d_car.py", line 38, in __init__
    self.data = scio.loadmat(str(path), struct_as_record=False, squeeze_me=True)['images']
  File "/usr/local/lib/python3.7/dist-packages/scipy/io/matlab/mio.py", line 224, in loadmat
    with _open_file_context(file_name, appendmat) as f:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/dist-packages/scipy/io/matlab/mio.py", line 17, in _open_file_context
    f, opened = _open_file(file_like, appendmat, mode)
  File "/usr/local/lib/python3.7/dist-packages/scipy/io/matlab/mio.py", line 45, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: '/content/unicorn-main/datasets/pascal_3d/ucmr_anno/data/car_train.mat'

i just want to know where the location of ucmr_anno file install so i can fix it and know the path

i spend so much time searching  ucmr_anno file in colab files

help me please and thank for the work

**Comment by monniert** [comment]
Hi @Jawadllo, thanks for reaching out for the issue!

Have you downloaded the p3d_car dataset using the `download_data.sh` script? if so the dataset should be located at `unicorn/datasets/pascal_3d`, and if not, you should track where these files actually went. Otherwise, for this specific files, you can use the following lines to download and rename the files:

```
wget https://people.eecs.berkeley.edu/~shubham-goel/projects/ucmr/cachedir-others.tar.gz && tar -vzxf cachedir-others.tar.gz
mv cachedir/p3d/data/car_val.mat cachedir/p3d/data/car_test.mat  # XXX renamed to correspond to the real test split
mv cachedir/p3d datasets/pascal_3d/ucmr_anno
```

From the stacktrace, you need to put the files at `unicorn-main/datasets/pascal_3d/ucmr_anno`

**Comment by Jawadllo** [comment]
thanks found it
